#In this section we're going to look at the most fundamental concepts of using TensorFlow
 More specifically
  Introduction to tensors
  Getting information from tensors
  Tensors and Numpy
  using @tf.function (way to speed up regular Python function)
  using GPU with TensorFlow(orTPUs)
  Exercises


##Introduction to  Tensors

In [ ]:
#Import Tensorflow

import tensorflow as tf
import numpy as np

print(tf.__version__)

2.19.0


In [ ]:
#create our first Tensors usinf tf.constant()

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Checking the number of dimensions of a Tensor(ndim stands for number of dimensions)

scalar.ndim


0

In [ ]:
#create a vector

vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim


1

In [ ]:
#create a matrix
matrix=tf.constant([[7,10],
 [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [10,  7]], dtype=int32)>

In [ ]:
matrix.ndim


2

In [ ]:
#crete another matrix
another_matrix=tf.constant([[4.,7.],
                            [10.,7.],
                            [10.,7.]
                            ] , dtype=tf.float16 #specifying the data type
)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  7.],
       [10.,  7.],
       [10.,  7.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets create a tensor
tensor=tf.constant([
                     [[1,2,4],[3,4,5]],
                     [[3,2,1],[7,6,5]],
                     [[2,3,4],[4,5,6]]
                     ])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 4],
        [3, 4, 5]],

       [[3, 2, 1],
        [7, 6, 5]],

       [[2, 3, 4],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've done so far


*   List item
*   scalar: a single digit
*   vector: a quantity with magnitude and direction
*   matrix: a 2-dimensional array of values
*   tensor: an n-dimensional array

16/07/2025
A recap of what we did the previous lesson


*   scalar
*   vector

*   matrix
*  Tensor




In [ ]:
import tensorflow as tf

In [ ]:
scalar=tf.constant(5)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
scalar.ndim


0

In [ ]:
vector=tf.constant([2,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

###Creating changeable tensors using the `tf.variable()`

In [ ]:
#creating changeable and unchangeable tensors

changeable_tensor=tf.Variable([10,7])

unchangeable_tensor=tf.constant([10,7])


changeable_tensor,unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0]
changeable_tensor[1]

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
changeable_tensor[0].assign(7)



changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[1].assign(3)


AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

**Generating/creating random tensors (with a seed) **


In [ ]:
random_1=tf.random.Generator.from_seed(15)
random_1=random_1.normal(shape=(3,2))
random_1


In [ ]:
random_2=tf.random.Generator.from_seed(15)
random_2=random_2.normal(shape=(4,5))
random_2

In [ ]:
random_3=tf.random.Generator.from_seed(7)
random_3=random_3.normal(shape=(2,3))

random_3


# **Comparing the behaviour and equallity under different seed conditions **

In [ ]:
#are they equal
random_4=tf.random.Generator.from_seed(2)
random_4=random_4.normal(shape=(4,5))

random_5=tf.random.Generator.from_seed(10)
random_5=random_5.normal(shape=(4,5))

random_4,random_5,random_4==random_5

its clear that when you change the shape of the tensor ,the equality test doesn't come out

some revision

In [ ]:
import tensorflow as tf
print(tf.__version__)

In [ ]:
random_3=tf.random.Generator.from_seed(3)
random_3=random_3.normal(shape=(4,5))
random_3

**shuffling the order of Tensors**===(so why might this be neccessary)
--
suppose we want to train a Neural Network to identiffy some things from a huge data set if we pass in the first category and then the second ,the neural network might start adapting to the first categories pattterns only to be shocked when it realises it has to learn category 2 also .conversely if the groups are mixed beforehand then the NeuralNetwork will have to figure them out by itself and therefore not get spooked by happenings .

In [ ]:
##Shuffling ;so that the inherrent order doesn't affect learning
shuffle=tf.constant([[3,4],[5,6],[9,4]])

tf.random.shuffle(shuffle)

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(shuffle,seed=43)

#**What is a seed in TF **
A seed" in TensorFlo "seed" in TensorFlow is a number you set to make random actions in your code predictable and repeatable. It ensures that if you run your code today, tomorrow, or a year from now, and someone else runs it on their computer, as long as they use the same seed, they'll get the same "random" outcomes, and thus, more consistent and reproducible results for your model training and experiments.


>if we want to shuffle our tensors according to some pattern ,we use the global as well as operation seed of the same value
--
this is crucial if we want to have a shuffle in a discrete order

In [ ]:
import tensorflow as tf


In [ ]:
###making tensors from numpy arrays
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

#converting Numpy arrays into Tensors

In [ ]:
import numpy as np
value_A=np.array((3,4))
value_A

array([3, 4])

In [ ]:
numpy_1=np.arange(2,10,dtype=int)   #list nos within the range of 2 to 10
numpy_1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:

vector=tf.constant(numpy_1)  #converting numpy array to tensor
vector(shape=(1,2))          #trying to make some shape out of it
vector


TypeError: 'tensorflow.python.framework.ops.EagerTensor' object is not callable

In [ ]:
#--so objet not callable lets try sth cranky here
tf.constant(numpy_1)

#it works without assignment

In [ ]:
#with assignment
variable=tf.constant(numpy_1)
variable
#it also works with assignment and calling

In [ ]:
#what if we take the variable and try to mess up its shape

variable(shape=(1,2))
variable
#so this is the not so callable thing ,cannot / there's a way
#the way is a function tf.reshape -it returns a new tensor with shape changed

In [ ]:
#tf.reshape is the key to shaping a tensor ,but tensors cannot be shappped bcoz they're by default ,so we can only reshape em
tf.reshape(variable,(2,4))

NameError: name 'variable' is not defined

In [ ]:
#well check this out guys
# if we pass 2 parameters to the tf.constant()?
tf.constant(numpy_1,shape=(4,2))

#so that means that using tf.reshape is actually an overkill for this

#so now we are going to the section of getting information from our tensors



1.   rank      :number of tensor axes
2.   shape     :the number of elements on each individual axis
3. axis/dimension :refers to an individual axis
4. size        :total number of elements entire structure  

so mathematically,ranks can be infinite ,but in empirical aspect of computation:


---

its resource intensive and slow even to a highly optimized AI/ML framework ,the processors



In [ ]:
#creating a 4 rank tensor
rank_4_tensor=tf.zeros(shape=(2,3,4,5))



In [ ]:
rank_4_tensor.shape,rank_4_tensor.ndim,#rank_4_tensor.size

In [ ]:
rank_4_tensor.shape

In [ ]:
rank_4_tensor.ndim

In [ ]:
tf.size(rank_4_tensor)

In [ ]:
#Extracting varius Tensor attributes from a tensor

print("The shape of the Tensor:",rank_4_tensor.shape)
print("The data type :",rank_4_tensor.dtype)
print("The size without fluff: ",tf.size(rank_4_tensor).numpy())
print("The no of dimensions: ",rank_4_tensor.ndim)
print("The size of the Tensor :",tf.size(rank_4_tensor))
print("The shape of the first axis: ",rank_4_tensor.shape[0])

NameError: name 'rank_4_tensor' is not defined

## so we are dealing with indexing and expanding tensors
.indexing :retreiving data from a dimension


.expanding : increasing the size of the tensor

#INDEXING

In [ ]:
rank_3_tensor=tf.constant([[3,4],[4,6],[2,1]])
rank_3_tensor

In [ ]:
print("Dimensions :",rank_3_tensor.ndim)
print("Data Type  :",rank_3_tensor.dtype)
print("Size :",tf.size(rank_3_tensor).numpy())
print("Shape :",rank_3_tensor.shape)

In [ ]:
# indexing Tensors
#Get the fist item from first index of the first dimension
rank_3_tensor[:3,:1]


NameError: name 'rank_3_tensor' is not defined

In [ ]:
rank_3_tensor[:2,:2]

In [ ]:
rank_3_tensor[:2,:1]

In [ ]:
rank_3_tensor[1,:-1]

#EXPANDING
we use 2 ways to achieve this feat
 newaxis method and  expand format

In [ ]:
#the new axis method

rank_5_tensor=rank_4_tensor[...,tf.newaxis]
rank_5_tensor

#so it add a 1 dim length to the array

In [ ]:
rank_4_tensor_1=rank_3_tensor[...,tf.newaxis]
#rank_4_tensor_1
rank_3_tensor

NameError: name 'rank_3_tensor' is not defined

#tf.expand_dims()

In [ ]:
#then what is this that I've written my people ? and works
rank_4_tensor_2=tf.expand_dims(rank_3_tensor,-1)
rank_4_tensor_2

In [ ]:
#bcoz this is the right way of doing this stuff

rank_4_tensor_3=tf.expand_dims(rank_3_tensor,axis=1)
rank_4_tensor_3

In [ ]:
print("Dimensions of the tensor :",rank_3_tensor.ndim)
print('The shape of the tensor :',rank_3_tensor.shape)

In [ ]:
#what if we have axis as 2 ,what does that mean ?
#what are we doing here my good people
rank_4_tensor_4=tf.expand_dims(rank_3_tensor,axis=2)
rank_4_tensor_4

#Basic tensor operations --elementwise

they include + - * /  (normal arithimetic operations)

In [ ]:
#addition
tensor= tf.constant([[2,3],[3,4]])
tensor + 10

In [ ]:
tensor -10

so it follows that to have native/strong integration and running we need to use tensorflow functions as much as possible

In [ ]:
#
tf.add(tensor,5)

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[10, 20, 40],
        [30, 40, 50]],

       [[30, 20, 10],
        [70, 60, 50]],

       [[20, 30, 40],
        [40, 50, 60]]], dtype=int32)>

#matrix  multiplication
one of the most common tensor operations
it follows a set of rules for the matrix multiplication to work

In [ ]:
#tf.matmul() is the function

tf.matmul(tensor,tensor)

InvalidArgumentError: {{function_node __wrapped__BatchMatMulV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2,3], In[1]: [3,2,3] [Op:BatchMatMulV2] name: 

In [ ]:
tensor

rules are as follows:

#the inner numbers must match
#the new size is the same as the outer numbers

[3]x{4}  ...... {4}x[2]  ========> the resulting size=====> 3 x 2

In [ ]:
#lets create some matrices
y=tf.constant([[2,5,4],[7,9,1]])

x=tf.constant([[7,10],[2,3],[5,6]])

In [ ]:
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 5, 4],
       [7, 9, 1]], dtype=int32)>

In [ ]:
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 10],
       [ 2,  3],
       [ 5,  6]], dtype=int32)>

In [ ]:
tf.matmul(x,y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 84, 125,  38],
       [ 25,  37,  11],
       [ 52,  79,  26]], dtype=int32)>

##changing the shape of our tensors

tf.reshape  
tf.transpose

In [ ]:
x ,tf.reshape(x,shape=(2,3)),tf.transpose(x,)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7, 10],
        [ 2,  3],
        [ 5,  6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7, 10,  2],
        [ 3,  5,  6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  2,  5],
        [10,  3,  6]], dtype=int32)>)

In [ ]:
y ,tf.reshape(y,shape=(3,2)) ,tf.transpose(x,)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 5, 4],
        [7, 9, 1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [4, 7],
        [9, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  2,  5],
        [10,  3,  6]], dtype=int32)>)

##matrix multiplication is achieved by two methods
.tf.matmul();works for matxice multiplication  

.tf.dotproduct(); suitable for 1&2D multiplication but doesnt always work well for larger data sets  

In [ ]:
tf.matmul(tf.transpose(y),y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 53,  73,  15],
       [ 73, 106,  29],
       [ 15,  29,  17]], dtype=int32)>

In [ ]:
tf.tensordot(y,y ,axes=1 )

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul] name: 

In [ ]:
#performing tensor multiplication with x and Y transposed
tf.matmul(tf.transpose(y),x)

In [ ]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

####generally in matrix multiplication,when we have errors involving matrix alligment in axes we generally employ the use of tf.transpose instead of tf.reshape

#27:Changing datatype of a tensor

In [ ]:
#the  default is  int32 ,but it depends on the data that you have .
B=tf.constant([[1,7],[7.4,10]])
B.dtype

tf.float32

In [ ]:
c=tf.constant([[1,7],[7,10]])
c.dtype

tf.int32

Reduced precision =====>reduces the number of bits  needed to represent a number in scenarios where accuracy/precision isn't a priority.In return it leads to faster speeds of exec,high memory management ,low power consumption etc

##tf.cast()

In [ ]:
#Changing from float32 to float16(Reduced precision)

In [ ]:
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
d=tf.cast(c,dtype=tf.int16)
d

<tf.Tensor: shape=(2, 2), dtype=int16, numpy=
array([[ 1,  7],
       [ 7, 10]], dtype=int16)>

##Agregating tensors
the practice of condensing multiple tensors to a smaller value

In [ ]:
#tf.abs()  gets the absolute value of a tensor ie

D=tf.constant([-10,-7])



print('\nThe look of D is :\n',D)
print('\n The look of its absolute \n',tf.abs(D))


The look of D is :
 tf.Tensor([-10  -7], shape=(2,), dtype=int32)

 The look of its absolute 
 tf.Tensor([10  7], shape=(2,), dtype=int32)


In [ ]:
##Creating a random tensor with values between 0 to 100 of size 50

E=tf.constant(np.random.randint(0,100,size=50))

print("\n",E)
print("\n",tf.size(E))
print("\n",E.ndim)
print("\n",E.shape)


 tf.Tensor(
[26 40 65 49 31 66 61 27 13 58 42 33 98  4 90 55 24 88  6  4 71 96 14 20
 39 66 99 15 95 29 67 35 54 27 27 12 32 79  9 29 27 92  6 89 22 28 76 57
 65 57], shape=(50,), dtype=int64)

 tf.Tensor(50, shape=(), dtype=int32)

 1

 (50,)


In [ ]:
#find the max value
print("\nThe max value is :\n",tf.reduce_max(E))
#find the min value
print("\nThe min value is :\n",tf.reduce_min(E))
#find the mean
print("\nThe mean of E is :\n",tf.reduce_mean(E))
#find the sum of all tensor values
print("\nThe sum of the tensor values:\n",tf.reduce_sum(E))
#find the standard deviation--not working....
print("\nThe standard deviation of E is :\n",tf.math.reduce_std(E))
#find the variance ---also not working....
print("\nThe variance of E is :\n",tf.math.reduce_variance(E))



The max value is :
 tf.Tensor(99, shape=(), dtype=int64)

The min value is :
 tf.Tensor(4, shape=(), dtype=int64)

The mean of E is :
 tf.Tensor(46, shape=(), dtype=int64)

The sum of the tensor values:
 tf.Tensor(2314, shape=(), dtype=int64)


TypeError: Input must be either real or complex. Received integer type <dtype: 'int64'>.

In [ ]:
import tensorflow_probability as tfp

In [ ]:
#variance  real or complex means floats ??
print("\n Variance from math.reduce_variance :\n",tf.math.reduce_variance(tf.cast(E,dtype=tf.float32)))
print ("The variance from tfp.stats.variance :\n",tfp.stats.variance(tf.cast(E,dtype=tf.float32)))

In [ ]:
#standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))
print("\n STD  from math.reduce_std :\n",tf.math.reduce_std(tf.cast(E,dtype=tf.float64)))
print("\n STD  from tfp.stats.stddev :\n",tfp.stats.stddev(tf.cast(E,dtype=tf.float64)))

###in conclusion we have these diverse function performing the same thing :But I'm yet to know which  one is for which work

* .tfp.stats.stddev()

* .tf.math.reduce_std()

* .tfp.stats.variance()

* .tf.math.reduce_variance()

 ▶ point to notice is that the types must be taken into conciderations

##finding positional maximum and minimum

In [ ]:
#let's create a new tensor

F=tf.random.uniform(shape=[50])
F

In [ ]:
#finding the position of the max value(INDEX THAT IS )
#finding the position of the min value
tf.argmax(F) ,tf.argmin(F)



In [ ]:
#what are the values of in the indexes
F[tf.argmax(F)] ,F[tf.argmin(F)]

In [ ]:
#check for equality
assert tf.reduce_max(F)== F[tf.argmax(F)]#nothing happens

In [ ]:
#lets try this one
#because it runs silently ,is it True?

assert F[tf.argmax(F)] == tf.reduce_max(F)

##squeezing  1 dimensional tensors
gets rid of extra dimensions and reduces it back to its essence

In [ ]:
#lets start by creating a random tensor
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

##one hot_encodding

method of representing/converting categorical data in numerical format

.easier for neural networks

.compartibility with other algorithms

.performance

---
tf.one_hot(),

on value & off values allow you to specify what values will be displayed on either of the situations,not neccesarily 1 and 0 as is the norm .

In [ ]:
#create a list of some indices
some_list=[1,2,3,4]  #let's say they represent red,green,blue and white
some_list_1=[0,1,2,3]
some_list_2=[2,3,4,5]

In [ ]:
print("\narray [0,1,2,3]:\n",tf.one_hot(some_list_1,depth=3))
print("\narray [1,2,3,4]:\n",tf.one_hot(some_list,depth=3))
print("\narray [2,3,4,5]:\n",tf.one_hot(some_list_2,depth=3))
print("\n------------------------------------------\n")
print("array [0,1,2,3]\n",tf.one_hot(some_list_1,depth=4))
print("array [0,1,2,3]\n",tf.one_hot(some_list,depth=4))
print("array [0,1,2,3]\n",tf.one_hot(some_list_2,depth=4))


array [0,1,2,3]:
 tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)

array [1,2,3,4]:
 tf.Tensor(
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)

array [2,3,4,5]:
 tf.Tensor(
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(4, 3), dtype=float32)

------------------------------------------

array [0,1,2,3]
 tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
array [0,1,2,3]
 tf.Tensor(
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
array [0,1,2,3]
 tf.Tensor(
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)


There are other things to be learned but reserved for learning on demand/neccessity.

###exploring tensorflow and Numpy compartibility

tensorFlow integrates so well with Numpy

In [ ]:
#creating a tensor directly from a Numpy Array
J=tf.constant(np.array([3.,4.,5.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>

In [ ]:
#converting our tensor back to an Array
np.array(J),type(np.array(J))

(array([3., 4., 5.]), numpy.ndarray)

In [ ]:
#converting tensor J to a numpy
J.numpy() ,type (J.numpy())

(array([3., 4., 5.]), numpy.ndarray)

This integration allows easy switching when one framework works better for a particular job than the other

In [ ]:
#However they have different dtypes
tensor_j=tf.constant(np.array([3.,4.]))
tnsor_j=tf.constant([3.,4.])

tensor_j.dtype,tnsor_j.dtype


(tf.float64, tf.float32)

##making sure our codes run fast


In [ ]:
import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Fri Aug 15 08:23:04 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----